import React, { useState } from 'react';
import { X, Copy, Check, Search } from 'lucide-react';

interface FormulaDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

interface FormulaCard {
  name: string;
  formula: string;
  terms: string;
  siUnit: string;
  notes: string;
}

const FORMULAS_LIST: FormulaCard[] = [
  {
    name: 'Electric Current',
    formula: 'I = Q / t',
    terms: 'I = current, Q = charge, t = time',
    siUnit: 'Ampere (A) = C/s',
    notes: 'Conventional current flows from (+) to (−); electrons drift from (−) to (+).'
  },
  {
    name: 'Electric Potential Difference',
    formula: 'V = W / Q',
    terms: 'V = voltage, W = work done, Q = charge',
    siUnit: 'Volt (V) = J/C',
    notes: 'Measured with a voltmeter connected strictly in PARALLEL.'
  },
  {
    name: 'Ohm’s Law',
    formula: 'V = I · R',
    terms: 'V = voltage, I = current, R = resistance',
    siUnit: 'Ohm (Ω) = V/A',
    notes: 'Valid at constant temperature for ohmic conductors. V-I graph is a straight line.'
  },
  {
    name: 'Resistance & Dimensions',
    formula: 'R = ρ · (l / A)',
    terms: 'R = resistance, ρ = resistivity, l = length, A = cross-sectional area',
    siUnit: 'R in Ohms (Ω)',
    notes: 'Resistance is directly proportional to length (R ∝ l) and inversely to area (R ∝ 1/A).'
  },
  {
    name: 'Specific Resistivity',
    formula: 'ρ = (R · A) / l',
    terms: 'ρ = resistivity, R = resistance, A = area, l = length',
    siUnit: 'Ohm-metre (Ω·m)',
    notes: 'Independent of wire shape/dimensions. Depends only on material and temperature.'
  },
  {
    name: 'Series Combination',
    formula: 'Rₛ = R₁ + R₂ + R₃',
    terms: 'Rₛ = total series resistance; V = V₁ + V₂ + V₃; I = constant',
    siUnit: 'Ohm (Ω)',
    notes: 'Equivalent resistance is always larger than the greatest single resistor.'
  },
  {
    name: 'Parallel Combination',
    formula: '1/Rₚ = 1/R₁ + 1/R₂ + 1/R₃',
    terms: 'For two: Rₚ = (R₁ · R₂) / (R₁ + R₂); V = constant; I = I₁ + I₂ + I₃',
    siUnit: 'Ohm (Ω)',
    notes: 'Equivalent resistance is always smaller than the smallest single resistor.'
  },
  {
    name: 'Electric Power',
    formula: 'P = W / t = V · I = V² / R = I² · R',
    terms: 'P = power, W = work, t = time, V = voltage, I = current, R = resistance',
    siUnit: 'Watt (W) = J/s = 1 V · 1 A',
    notes: 'Rate of doing electrical work or consuming electrical energy. P = W/t = V · I = V²/R = I² · R.'
  },
  {
    name: 'Joule’s Heating Effect (Joule Heat H)',
    formula: 'H = I² · R · t = I²Rt',
    terms: 'H = Joule heat, I = current, R = resistance, t = time in seconds',
    siUnit: 'Joule (J) [1 cal ≈ 4.184 J; 1 J ≈ 0.239 cal]',
    notes: 'Thermal energy generated by flowing current: H = I² · R · t. Doubling current produces FOUR times the heat.'
  },
  {
    name: 'Electrical Energy',
    formula: 'W = E = Electric Power × Time = P · t',
    terms: 'W = electrical work/energy, P = electric power, t = time, V = voltage, I = current',
    siUnit: 'Watt-second (W·s) / Joule (J); Commercial: Kilowatt-hour (kWh or Unit)',
    notes: 'W = E = P · t = V · I · t = I² · R · t = (V²/R) · t. Commercial unit: 1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ W·s = 3.6 × 10⁶ J.'
  },
  {
    name: 'Commercial Electrical Energy (kWh Conversion)',
    formula: '1 kWh = 1 Unit = 3.6 × 10⁶ J = 3.6 × 10⁶ W·s',
    terms: 'Energy (kWh) = (Power in Watts × Time in Hours) / 1000',
    siUnit: 'Kilowatt-hour (kWh) [Board of Trade Unit / 1 Unit]',
    notes: '1 kWh = 1000 W × 3600 s = 3,600,000 Watt-seconds (W·s) = 3.6 × 10⁶ Joules (J). NEVER call kWh a unit of power!'
  },
  {
    name: 'Quantization of Charge',
    formula: 'Q = n · e',
    terms: 'Q = total charge, n = number of electrons, e = 1.6 × 10⁻¹⁹ C',
    siUnit: 'Coulomb (C)',
    notes: 'In 1 Coulomb of charge, there are approx 6.25 × 10¹⁸ electrons.'
  }
];

export const FormulaDrawer: React.FC<FormulaDrawerProps> = ({ isOpen, onClose }) => {
  const [filter, setFilter] = useState('');
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  if (!isOpen) return null;

  const filtered = FORMULAS_LIST.filter(f =>
    f.name.toLowerCase().includes(filter.toLowerCase()) ||
    f.formula.toLowerCase().includes(filter.toLowerCase()) ||
    f.terms.toLowerCase().includes(filter.toLowerCase())
  );

  const handleCopy = (formula: string, index: number) => {
    navigator.clipboard.writeText(formula);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 1500);
  };

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="drawer-content w-full max-w-md bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 h-full flex flex-col p-6 shadow-2xl overflow-hidden transition-colors">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800">
          <div>
            <h2 className="text-lg font-bold text-slate-900 dark:text-white tracking-tight">AP SSC Formula Reference</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">Class 10 Physics • Chapter: Electricity</p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Search */}
        <div className="my-4 relative">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" />
          <input
            type="text"
            placeholder="Search formulas (e.g. Ohm, Power, Joule)..."
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-400"
          />
        </div>

        {/* Formula Cards */}
        <div className="flex-1 overflow-y-auto space-y-3 pr-1">
          {filtered.map((item, idx) => (
            <div key={idx} className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 hover:border-slate-700 transition-colors">
              <div className="flex items-center justify-between gap-2 mb-1.5">
                <span className="text-xs font-semibold text-amber-400">{item.name}</span>
                <button
                  onClick={() => handleCopy(item.formula, idx)}
                  className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-amber-400 transition-colors cursor-pointer"
                  title="Copy formula"
                >
                  {copiedIndex === idx ? (
                    <>
                      <Check className="w-3 h-3 text-emerald-400" />
                      <span className="text-emerald-400 text-[10px]">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3 h-3" />
                      <span className="text-[10px]">Copy</span>
                    </>
                  )}
                </button>
              </div>

              <div className="text-base sm:text-lg font-mono font-extrabold text-amber-300 bg-slate-950 py-2 px-3.5 rounded-xl border border-amber-400/40 my-2 tracking-wide shadow-xs">
                {item.formula}
              </div>

              <div className="text-[11px] text-slate-400 mt-2 space-y-1">
                <div><span className="text-slate-500">Terms:</span> {item.terms}</div>
                <div><span className="text-slate-500">SI Unit:</span> <span className="text-emerald-400 font-mono">{item.siUnit}</span></div>
                <div className="text-slate-300 italic pt-1 border-t border-slate-800/60">{item.notes}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
